# Generated by Django 4.2.7 on 2023-11-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_thread_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
