# Generated by Django 4.2.7 on 2023-11-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_remove_thread_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='image_thread'),
        ),
    ]
